N_QUBITS = 10  # 量子比特数量
POP_SIZE = 50  # 种群数量
N_LAYERS = 5  # 量子线路的层数
btsize = 64
nepoch = 40
ESL = 1.0  # 遗传算法中产生新cnot数量的超参数
cross_parents = 4  # 种群中选择出来交叉的数量
crossover_rate = 0.3  # 基因交叉的概率（交叉的cnot数量占个体总cnot数量的比例）
NUMBER_OF_GENERATIONS = 10  # 总的进化代数
SAVE_RESULT = True  # 将结果保存至本地
tournament_size = 3  # 同小组竞赛的数量
num_select = 1  # 选择环节胜出的个体数
num_dag = 20
num_KL = 5
n_classes = 8
train_pop = 5
use_cuda = False